schema-version: 2.0.2

package:
  name: configurable-http-proxy

advisories:
  - id: CVE-2023-26159
    aliases:
      - GHSA-jchw-25xp-jwwc
    events:
      - timestamp: 2024-02-18T07:19:23Z
        type: fixed
        data:
          fixed-version: 4.6.1-r1
