schema-version: 2.0.2

package:
  name: docker-compose

advisories:
  - id: CVE-2023-47108
    aliases:
      - GHSA-8pgv-569h-w5rw
    events:
      - timestamp: 2024-02-14T16:26:19Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: docker-compose
            componentID: 8ab2a5432a3c73fb
            componentName: go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc
            componentVersion: v0.45.0
            componentType: go-module
            componentLocation: /usr/bin/docker-compose
            scanner: grype
      - timestamp: 2024-02-21T07:10:19Z
        type: fixed
        data:
          fixed-version: 2.24.6-r0
