schema-version: "2"

package:
  name: haproxy-ingress

advisories:
  - id: CVE-2020-8552
    aliases:
      - GHSA-82hx-w2r5-c2wq
    events:
      - timestamp: 2023-09-19T16:42:13Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Go vulndb has marked this code NOT_IMPORTABLE.

  - id: CVE-2023-39325
    events:
      - timestamp: 2023-10-16T18:08:16Z
        type: fixed
        data:
          fixed-version: 0.14.5-r5

  - id: CVE-2023-3978
    events:
      - timestamp: 2023-10-16T18:09:23Z
        type: fixed
        data:
          fixed-version: 0.14.5-r5

  - id: CVE-2023-44487
    events:
      - timestamp: 2023-10-16T18:11:57Z
        type: fixed
        data:
          fixed-version: 0.14.5-r5
