schema-version: "2"

package:
  name: ingress-nginx-controller

advisories:
  - id: CVE-2022-41741
    aliases:
      - GHSA-3v5h-538g-pr7g
    events:
      - timestamp: 2023-09-13T18:17:39Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: CVE relates to NGINX module ngx_http_mp4_module which is not included in the package

  - id: CVE-2022-41742
    aliases:
      - GHSA-wj45-j4gh-fm3x
    events:
      - timestamp: 2023-09-13T18:20:22Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: CVE relates to NGINX module ngx_http_mp4_module which is not included in the package

  - id: CVE-2023-44487
    events:
      - timestamp: 2023-10-13T04:13:45Z
        type: fixed
        data:
          fixed-version: 1.9.3-r1
