schema-version: 2.0.1

package:
  name: kubernetes-ingress-defaultbackend

advisories:
  - id: CVE-2023-39325
    aliases:
      - GHSA-4374-p667-p6c8
    events:
      - timestamp: 2023-10-13T17:18:03Z
        type: fixed
        data:
          fixed-version: 1.25.1-r3
