schema-version: "2"

package:
  name: kubernetes-ingress-defaultbackend

advisories:
  - id: CVE-2023-39325
    events:
      - timestamp: 2023-10-13T17:18:03Z
        type: fixed
        data:
          fixed-version: 1.25.1-r3
