schema-version: "2"

package:
  name: nri-prometheus

advisories:
  - id: CVE-2023-39325
    events:
      - timestamp: 2023-10-16T18:52:16Z
        type: fixed
        data:
          fixed-version: 2.18.7-r3

  - id: CVE-2023-3978
    events:
      - timestamp: 2023-10-16T18:53:14Z
        type: fixed
        data:
          fixed-version: 2.18.7-r3

  - id: CVE-2023-44487
    events:
      - timestamp: 2023-10-16T18:54:05Z
        type: fixed
        data:
          fixed-version: 2.18.7-r3
