schema-version: "2"

package:
  name: prometheus-postgres-exporter

advisories:
  - id: CVE-2023-39325
    events:
      - timestamp: 2023-10-13T17:54:05Z
        type: fixed
        data:
          fixed-version: 0.14.0-r3

  - id: CVE-2023-3978
    events:
      - timestamp: 2023-10-13T17:57:41Z
        type: fixed
        data:
          fixed-version: 0.14.0-r3
