schema-version: 2.0.2

package:
  name: prometheus-beat-exporter

advisories:
  - id: CVE-2023-45289
    aliases:
      - GHSA-32ch-6x54-q4h9
    events:
      - timestamp: 2024-03-12T08:01:15Z
        type: fixed
        data:
          fixed-version: 0.4.0-r1
