schema-version: "2"

package:
  name: prometheus-mysqld-exporter

advisories:
  - id: CVE-2023-39325
    events:
      - timestamp: 2023-10-13T17:53:29Z
        type: fixed
        data:
          fixed-version: 0.15.0-r6

  - id: CVE-2023-3978
    events:
      - timestamp: 2023-10-13T17:57:06Z
        type: fixed
        data:
          fixed-version: 0.15.0-r6
