schema-version: "2"

package:
  name: prometheus-config-reloader

advisories:
  - id: CVE-2019-3826
    events:
      - timestamp: 2023-08-11T21:17:56Z
        type: false-positive-determination
        data:
          type: vulnerable-code-version-not-used
          note: This CVE only impacts prometheus 2.7 but our prometheus-config-reloader is using v0.46.0 Go library which is in fact prometheus 2.46

  - id: CVE-2023-40577
    aliases:
      - GHSA-v86x-5fm3-5p7j
    events:
      - timestamp: 2023-08-25T20:47:31Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: This vulnerability is an XSS flaw affecting alertmanager as a server, not when imported as a library.
