schema-version: "2"

package:
  name: prometheus-elasticsearch-exporter

advisories:
  - id: CVE-2023-39325
    events:
      - timestamp: 2023-10-13T17:53:02Z
        type: fixed
        data:
          fixed-version: 1.6.0-r6

  - id: CVE-2023-3978
    events:
      - timestamp: 2023-10-13T17:56:47Z
        type: fixed
        data:
          fixed-version: 1.6.0-r6
