schema-version: 2.0.1

package:
  name: prometheus-stackdriver-exporter

advisories:
  - id: CVE-2022-41723
    aliases:
      - GHSA-vvpx-j8f3-3w6h
    events:
      - timestamp: 2023-05-02T22:52:07Z
        type: fixed
        data:
          fixed-version: 0.13.0-r0

  - id: CVE-2023-45283
    events:
      - timestamp: 2023-11-07T19:36:22Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CVE-2023-45284
    events:
      - timestamp: 2023-11-07T19:36:24Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows
