schema-version: "2"

package:
  name: prometheus

advisories:
  - id: CVE-2023-40577
    events:
      - timestamp: 2023-08-25T20:46:25Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: This vulnerability is an XSS flaw affecting alertmanager as a server not the library.
