schema-version: 2.0.1

package:
  name: prometheus-adapter

advisories:
  - id: CVE-2023-39325
    aliases:
      - GHSA-4374-p667-p6c8
    events:
      - timestamp: 2023-10-13T17:52:12Z
        type: fixed
        data:
          fixed-version: 0.11.1-r3

  - id: CVE-2023-3978
    aliases:
      - GHSA-2wrh-6pvc-2jm9
    events:
      - timestamp: 2023-10-13T17:56:24Z
        type: fixed
        data:
          fixed-version: 0.11.1-r3

  - id: CVE-2023-44487
    aliases:
      - GHSA-m425-mq94-257g
      - GHSA-qppj-fm5r-hxr3
    events:
      - timestamp: 2023-11-06T23:30:58Z
        type: fixed
        data:
          fixed-version: 0.11.1-r4

  - id: CVE-2023-45142
    aliases:
      - GHSA-rcjv-mgp8-qvmr
    events:
      - timestamp: 2023-11-06T23:32:21Z
        type: fixed
        data:
          fixed-version: 0.11.1-r4
