schema-version: "2"

package:
  name: prometheus-mongodb-exporter

advisories:
  - id: CVE-2023-39325
    events:
      - timestamp: 2023-10-13T17:53:18Z
        type: fixed
        data:
          fixed-version: 0.39.0-r4

  - id: CVE-2023-3978
    events:
      - timestamp: 2023-10-13T17:56:58Z
        type: fixed
        data:
          fixed-version: 0.39.0-r4
