schema-version: "2"

package:
  name: prometheus-node-exporter

advisories:
  - id: CVE-2023-39325
    events:
      - timestamp: 2023-10-13T17:53:41Z
        type: fixed
        data:
          fixed-version: 1.6.1-r6

  - id: CVE-2023-3978
    events:
      - timestamp: 2023-10-13T17:57:16Z
        type: fixed
        data:
          fixed-version: 1.6.1-r6
