schema-version: "2"

package:
  name: prometheus-adapter

advisories:
  - id: CVE-2023-39325
    events:
      - timestamp: 2023-10-13T17:52:12Z
        type: fixed
        data:
          fixed-version: 0.11.1-r3

  - id: CVE-2023-3978
    events:
      - timestamp: 2023-10-13T17:56:24Z
        type: fixed
        data:
          fixed-version: 0.11.1-r3
