package:
  name: prometheus-config-reloader

advisories:
  CVE-2019-3826:
    - timestamp: 2023-08-11T14:17:56.238481-07:00
      status: not_affected
      justification: vulnerable_code_not_present
      impact: This CVE only impacts prometheus 2.7 but our prometheus-config-reloader is using v0.46.0 Go library which is in fact prometheus 2.46
