package:
  name: prometheus-stackdriver-exporter

secfixes:
  0.13.0-r0:
    - CVE-2022-41723

advisories:
  CVE-2022-41723:
    - timestamp: 2023-05-02T22:52:07.740978573Z
      status: fixed
      fixed-version: 0.13.0-r0
