package:
  name: prometheus

advisories:
  CVE-2023-40577:
    - timestamp: 2023-08-25T13:46:25.775137-07:00
      status: not_affected
      justification: vulnerable-code-not-included-in-package
      impact: This vulnerability is an XSS flaw affecting alertmanager as a server not the library.
