schema-version: 2.0.1

package:
  name: prometheus-mongodb-exporter

advisories:
  - id: CVE-2023-39325
    aliases:
      - GHSA-4374-p667-p6c8
    events:
      - timestamp: 2023-10-13T17:53:18Z
        type: fixed
        data:
          fixed-version: 0.39.0-r4

  - id: CVE-2023-3978
    aliases:
      - GHSA-2wrh-6pvc-2jm9
    events:
      - timestamp: 2023-10-13T17:56:58Z
        type: fixed
        data:
          fixed-version: 0.39.0-r4

  - id: CVE-2023-45283
    events:
      - timestamp: 2023-11-07T19:35:57Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CVE-2023-45284
    events:
      - timestamp: 2023-11-07T19:35:58Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows
