schema-version: 2.0.2

package:
  name: prometheus-2.45

advisories:
  - id: GHSA-jq35-85cj-fj4p
    events:
      - timestamp: 2024-03-02T08:06:11Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: prometheus-2.45-bitnami-compat
            componentID: cf0b0f7160c2250e
            componentName: github.com/docker/docker
            componentVersion: v24.0.2+incompatible
            componentType: go-module
            componentLocation: /opt/bitnami/prometheus/bin/prometheus
            scanner: grype
