schema-version: 2.0.1

package:
  name: prometheus-elasticsearch-exporter

advisories:
  - id: CVE-2023-39325
    aliases:
      - GHSA-4374-p667-p6c8
    events:
      - timestamp: 2023-10-13T17:53:02Z
        type: fixed
        data:
          fixed-version: 1.6.0-r6
      - timestamp: 2023-10-18T03:55:31Z
        type: fixed
        data:
          fixed-version: 1.6.0-r7

  - id: CVE-2023-3978
    aliases:
      - GHSA-2wrh-6pvc-2jm9
    events:
      - timestamp: 2023-10-13T17:56:47Z
        type: fixed
        data:
          fixed-version: 1.6.0-r6
      - timestamp: 2023-10-18T03:55:16Z
        type: fixed
        data:
          fixed-version: 1.6.0-r7

  - id: CVE-2023-44487
    aliases:
      - GHSA-qppj-fm5r-hxr3
    events:
      - timestamp: 2023-10-18T03:55:41Z
        type: fixed
        data:
          fixed-version: 1.6.0-r7

  - id: CVE-2023-45283
    events:
      - timestamp: 2023-11-07T19:35:54Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CVE-2023-45284
    events:
      - timestamp: 2023-11-07T19:35:55Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows
