schema-version: 2.0.1

package:
  name: prometheus-alertmanager

advisories:
  - id: CVE-2023-39325
    aliases:
      - GHSA-4374-p667-p6c8
    events:
      - timestamp: 2023-10-13T17:52:53Z
        type: fixed
        data:
          fixed-version: 0.26.0-r4

  - id: CVE-2023-3978
    aliases:
      - GHSA-2wrh-6pvc-2jm9
    events:
      - timestamp: 2023-10-13T17:56:37Z
        type: fixed
        data:
          fixed-version: 0.26.0-r4

  - id: CVE-2023-40577
    aliases:
      - GHSA-v86x-5fm3-5p7j
    events:
      - timestamp: 2023-08-25T20:39:59Z
        type: fixed
        data:
          fixed-version: 0.26.0-r0
