schema-version: "2"

package:
  name: prometheus-pushgateway

advisories:
  - id: CVE-2023-39325
    events:
      - timestamp: 2023-10-13T17:54:17Z
        type: fixed
        data:
          fixed-version: 1.6.2-r3

  - id: CVE-2023-3978
    events:
      - timestamp: 2023-10-13T17:57:59Z
        type: fixed
        data:
          fixed-version: 1.6.2-r3
