schema-version: "2"

package:
  name: prometheus-stackdriver-exporter

advisories:
  - id: CVE-2022-41723
    events:
      - timestamp: 2023-05-02T22:52:07Z
        type: fixed
        data:
          fixed-version: 0.13.0-r0
