schema-version: 2.0.1

package:
  name: prometheus-pushgateway

advisories:
  - id: CVE-2023-39325
    aliases:
      - GHSA-4374-p667-p6c8
    events:
      - timestamp: 2023-10-13T17:54:17Z
        type: fixed
        data:
          fixed-version: 1.6.2-r3

  - id: CVE-2023-3978
    aliases:
      - GHSA-2wrh-6pvc-2jm9
    events:
      - timestamp: 2023-10-13T17:57:59Z
        type: fixed
        data:
          fixed-version: 1.6.2-r3
