schema-version: "2"

package:
  name: prometheus-statsd-exporter

advisories:
  - id: CVE-2023-39325
    events:
      - timestamp: 2023-10-13T17:54:30Z
        type: fixed
        data:
          fixed-version: 0.24.0-r3

  - id: CVE-2023-3978
    events:
      - timestamp: 2023-10-13T17:58:10Z
        type: fixed
        data:
          fixed-version: 0.24.0-r3
