package:
  name: py3-configobj

advisories:
  CVE-2023-26112:
    - timestamp: 2023-07-21T08:41:52.106634-04:00
      status: not_affected
      justification: vulnerable_code_not_present
      impact: The maintainers correctly deemed this to not be a vulnerability given it requires the system operator to enter the incorrect value.
