schema-version: "2"

package:
  name: skaffold

advisories:
  - id: CVE-2023-33199
    aliases:
      - GHSA-frqx-jfcm-6jjr
    events:
      - timestamp: 2023-08-02T17:03:24Z
        type: detection
        data:
          type: manual
      - timestamp: 2023-08-02T17:04:18Z
        type: fixed
        data:
          fixed-version: 2.6.2-r1
