schema-version: 2.0.2

package:
  name: skaffold

advisories:
  - id: CVE-2023-33199
    aliases:
      - GHSA-frqx-jfcm-6jjr
    events:
      - timestamp: 2023-08-02T17:03:24Z
        type: detection
        data:
          type: manual
      - timestamp: 2023-08-02T17:04:18Z
        type: fixed
        data:
          fixed-version: 2.6.2-r1

  - id: CVE-2023-39325
    aliases:
      - GHSA-4374-p667-p6c8
    events:
      - timestamp: 2023-10-15T20:48:25Z
        type: fixed
        data:
          fixed-version: 2.8.0-r4

  - id: CVE-2023-3978
    aliases:
      - GHSA-2wrh-6pvc-2jm9
    events:
      - timestamp: 2023-10-15T20:48:33Z
        type: fixed
        data:
          fixed-version: 2.8.0-r4

  - id: CVE-2023-44487
    aliases:
      - GHSA-qppj-fm5r-hxr3
    events:
      - timestamp: 2023-10-15T20:48:42Z
        type: fixed
        data:
          fixed-version: 2.8.0-r4

  - id: CVE-2023-45283
    aliases:
      - GHSA-vvjp-q62m-2vph
    events:
      - timestamp: 2023-11-07T19:37:51Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: CVE-2023-45284
    aliases:
      - GHSA-rq3x-83w4-p28c
    events:
      - timestamp: 2023-11-07T19:37:52Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: Only affects Windows

  - id: GHSA-7ww5-4wqc-m92c
    events:
      - timestamp: 2024-01-13T07:21:09Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: skaffold
            componentID: 3644179ba8ac321e
            componentName: github.com/containerd/containerd
            componentVersion: v1.7.2
            componentType: go-module
            componentLocation: /usr/bin/skaffold
            scanner: grype

  - id: GHSA-9763-4f94-gfch
    events:
      - timestamp: 2024-01-10T01:50:57Z
        type: fixed
        data:
          fixed-version: 2.10.0-r1
