schema-version: 2.0.2

package:
  name: traefik-3.2

advisories:
  - id: CGA-j4v3-whmm-486j
    aliases:
      - CVE-2024-28180
      - GHSA-c5q2-7r4c-mv6g
    events:
      - timestamp: 2024-11-01T17:01:29Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: traefik-3.2
            componentID: 5c0b53c63191a528
            componentName: gopkg.in/square/go-jose.v2
            componentVersion: v2.5.1
            componentType: go-module
            componentLocation: /usr/bin/traefik
            scanner: grype
      - timestamp: 2024-11-06T15:15:28Z
        type: pending-upstream-fix
        data:
          note: There is no fix for dependency gopkg.in/square/go-jose.v2 and a fix for this CVE would need code changes to replace the affected dependendency.

  - id: CGA-pw97-9g4p-mg7w
    aliases:
      - CVE-2024-51744
      - GHSA-29wx-vh33-7x7r
    events:
      - timestamp: 2024-11-05T10:03:04Z
        type: detection
        data:
          type: scan/v1
          data:
            subpackageName: traefik-3.2
            componentID: 18620a0c8e001111
            componentName: github.com/golang-jwt/jwt/v4
            componentVersion: v4.5.0
            componentType: go-module
            componentLocation: /usr/bin/traefik
            scanner: grype
      - timestamp: 2024-11-06T15:14:49Z
        type: fixed
        data:
          fixed-version: 3.2.0-r1
