schema-version: 2.0.1

package:
  name: traefik

advisories:
  - id: CVE-2021-41803
    aliases:
      - GHSA-hr3v-8cp3-68rf
    events:
      - timestamp: 2023-03-07T16:51:57Z
        type: fixed
        data:
          fixed-version: 2.9.8-r1

  - id: CVE-2022-23469
    aliases:
      - GHSA-h2ph-vhm7-g4hp
    events:
      - timestamp: 2023-01-29T16:56:03Z
        type: fixed
        data:
          fixed-version: 2.9.6-r0

  - id: CVE-2022-40716
    aliases:
      - GHSA-m69r-9g56-7mv8
    events:
      - timestamp: 2023-03-07T16:52:26Z
        type: fixed
        data:
          fixed-version: 2.9.8-r1

  - id: CVE-2022-46153
    aliases:
      - GHSA-468w-8x39-gj5v
    events:
      - timestamp: 2023-01-29T16:56:03Z
        type: fixed
        data:
          fixed-version: 2.9.6-r0

  - id: CVE-2023-2253
    aliases:
      - GHSA-hqxw-f8mx-cpmw
    events:
      - timestamp: 2023-05-17T21:12:08Z
        type: fixed
        data:
          fixed-version: 2.10.1-r2

  - id: CVE-2023-44487
    events:
      - timestamp: 2023-10-13T12:27:29Z
        type: fixed
        data:
          fixed-version: 2.10.5-r0

  - id: GHSA-jq35-85cj-fj4p
    events:
      - timestamp: 2023-10-31T20:04:04Z
        type: false-positive-determination
        data:
          type: vulnerable-code-not-included-in-package
          note: This vulnerability is in the container runtime itself, not clients of the container runtime.
