schema-version: "2"

package:
  name: traefik

advisories:
  - id: CVE-2021-41803
    events:
      - timestamp: 2023-03-07T16:51:57Z
        type: fixed
        data:
          fixed-version: 2.9.8-r1

  - id: CVE-2022-23469
    events:
      - timestamp: 2023-01-29T16:56:03Z
        type: fixed
        data:
          fixed-version: 2.9.6-r0

  - id: CVE-2022-40716
    events:
      - timestamp: 2023-03-07T16:52:26Z
        type: fixed
        data:
          fixed-version: 2.9.8-r1

  - id: CVE-2022-46153
    events:
      - timestamp: 2023-01-29T16:56:03Z
        type: fixed
        data:
          fixed-version: 2.9.6-r0

  - id: CVE-2023-2253
    events:
      - timestamp: 2023-05-17T21:12:08Z
        type: fixed
        data:
          fixed-version: 2.10.1-r2
