issuer: https://token.actions.githubusercontent.com
subject: repo:wolfi-dev/advisories:ref:refs/heads/main
claim_pattern:
  job_workflow_ref: wolfi-dev/advisories/.github/workflows/digestabot.yaml@refs/heads/main

permissions:
  contents: write
  pull_requests: write
  workflows: write
