name: automated-pr-review
on:
  workflow_dispatch:
  schedule:
    - cron: '42 * * * *'

jobs:
  enable-auto-merge:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write # needed for Octo STS federation

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - uses: chainguard-dev/octo-sts-action@6177b4481c00308b3839969c3eca88c96a91775f # v1.0.0
        id: octo-sts
        with:
          scope: wolfi-dev/advisories
          identity: enable-auto-merge

      - run: |
          ./scripts/enable-auto-merge.sh ${{ github.repository }}
        env:
          GH_TOKEN: ${{ steps.octo-sts.outputs.token }}

  review-pr:
    runs-on: ubuntu-latest

    needs: enable-auto-merge

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - run: |
          ./scripts/review-prs.sh ${{ github.repository }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
