name: Build and publish YAML

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-publish:
    name: Build and publish YAML
    runs-on: ubuntu-latest
    if: github.repository == 'wolfi-dev/advisories'

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: wolfi-dev/actions/build-and-publish-yaml@add-build-and-publish-yaml
        with:
          workload_identity_provider: "projects/618116202522/locations/global/workloadIdentityPools/prod-shared-e350/providers/prod-shared-gha"
          service_account: "prod-images-ci@prod-images-c6e5.iam.gserviceaccount.com"
          project_id: prod-images-c6e5
          wolfictl_args: "advisory export --advisories-repo-dir . --format yaml -o advisories.yaml"
          # gcs_apk_bucket_name: wolfi-production-registry-destination
          gcs_apk_bucket_name: temp-testing-shared-actions
          gcs_apk_directory_name: os

      # - name: Post failure notice to Slack
      #   uses: rtCamp/action-slack-notify@b24d75fe0e728a4bf9fc42ee217caa686d141ee8 # ratchet:rtCamp/action-slack-notify@v2.2.1
      #   if: ${{ failure() }}
      #   env:
      #     SLACK_ICON: http://github.com/chainguard-dev.png?size=48
      #     SLACK_USERNAME: guardian
      #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
      #     SLACK_CHANNEL: 'cve'
      #     SLACK_COLOR: '#8E1600'
      #     MSG_MINIMAL: 'true'
      #     SLACK_TITLE: Build/Publish YAML for ${{ github.repository }} failed!
      #     SLACK_MESSAGE: |
      #       For detailed logs: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
