name: Image digest update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

jobs:
  image-update:
    name: Image digest update
    runs-on: ubuntu-latest

    permissions:
      contents: read # needed to checkout, but then we rely on the PAT.
      id-token: write # needed to request an OIDC token for commit signing.

    steps:
    - uses: actions/checkout@v4
    - uses: chainguard-dev/actions/digesta-bot@main
      with:
        token: ${{ secrets.DIGEST_BOT_WOLFI_PAT }}
