name: Lint

on:
  pull_request:
    branches: ['main']
  push:
    branches:
      - gh-readonly-queue/main/**

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v3

    - name: Check YAML formatting
      id: lint-yaml
      uses: docker://ghcr.io/wolfi-dev/wolfictl:latest@sha256:3bd0aa32e4b06c7d14a22c42dcef84cbf73c72c1f6b738a44d3a39c18ea4e874
      with:
        entrypoint: wolfictl
        args: lint yam
