name: Lint

on:
  pull_request:
    branches: ['main']
  push:
    branches:
      - gh-readonly-queue/main/**

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v3

    - name: Check YAML formatting
      id: lint-yaml
      uses: docker://ghcr.io/wolfi-dev/wolfictl:latest@sha256:1b3ff62685952d3f776ccd526bc1ee8fd0b27cc28d5ccab8443f4ea355067840
      with:
        entrypoint: wolfictl
        args: lint yam

    - name: Check secfixes synchronization
      id: sync-secfixes
      uses: docker://ghcr.io/wolfi-dev/wolfictl:latest@sha256:1b3ff62685952d3f776ccd526bc1ee8fd0b27cc28d5ccab8443f4ea355067840
      with:
        entrypoint: wolfictl
        args: "advisory sync-secfixes --warn"
