name: Lint

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - gh-readonly-queue/main/**

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v3

    - name: Check YAML formatting
      id: lint-yaml
      uses: docker://ghcr.io/wolfi-dev/sdk:latest@sha256:5e5ab00f38c01dd234e29861994e2454edc52475feb3b452a9c4025359887b87
      with:
        entrypoint: wolfictl
        args: lint yam

  misspell:
    name: Misspell
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3

      - uses: reviewdog/action-misspell@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_error: true
          locale: "US"
