name: Lint

on:
  pull_request:
    branches: ['main']
  push:
    branches:
      - gh-readonly-queue/main/**

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v3

    - name: Check YAML formatting
      id: lint-yaml
      uses: docker://ghcr.io/wolfi-dev/wolfictl:latest@sha256:77c043b94ae01d1fa5d06fffb2ce70ecc564d3d52c452696fdf23b4d71999250
      with:
        entrypoint: wolfictl
        args: lint yam
