name: Lint

on:
  pull_request:
    branches: ['main']
  push:
    branches:
      - gh-readonly-queue/main/**

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v3

    - name: Check YAML formatting
      id: lint-yaml
      uses: docker://ghcr.io/wolfi-dev/sdk:latest@sha256:3bcb632e839f343c7a71f8c9301886462a43239b1d3ddd30fbfa4e3a7d4fbeb7
      with:
        entrypoint: wolfictl
        args: lint yam
