name: Validate

on:
  pull_request:
    branches: ['main']
  push:
    branches:
      - gh-readonly-queue/main/**

jobs:
  lint:
    name: Validate
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v3

    - name: Validate advisory data
      id: validate
      uses: docker://ghcr.io/wolfi-dev/sdk:latest@sha256:d7b6705864edf4873513e6bcacc0937f2f61385f4dacc9c9f07c3d4be8c6c9b1
      with:
        entrypoint: wolfictl
        args: advisory validate --no-distro-detection --advisories-repo-dir .
