name: Validate

on:
  pull_request_target:
    branches: ['main']
  push:
    branches:
      - gh-readonly-queue/main/**

jobs:
  lint:
    name: Validate
    runs-on: ubuntu-latest
    container:
      image: docker://ghcr.io/wolfi-dev/sdk:latest@sha256:743adc4a75b41834fe9649870017f3011c8b7d2e7a94030cc97cd39ccf117be9

    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        path: './wolfi-advisories'

    - name: 'Clone Wolfi packages repository'
      uses: actions/checkout@v4
      with:
        repository: 'wolfi-dev/os'
        fetch-depth: 0
        path: './wolfi-packages'
        ref: 'main'

    - name: Validate advisory data
      id: validate
      working-directory: ./wolfi-advisories
      env:
        GITHUB_TOKEN: ${{ secrets.WOLFI_BOT_PAT_ADVISORIES }}
      run: |
        fork_point=$(git merge-base --fork-point refs/remotes/origin/${{ github.base_ref }} HEAD || git rev-parse HEAD)
        echo "fork point will be $fork_point"

        wolfictl adv validate \
          --skip-alias \
          --no-distro-detection \
          --advisories-repo-dir . \
          --advisories-repo-url "https://github.com/${{ github.repository }}" \
          --advisories-repo-base-hash "$fork_point" \
          --distro-repo-dir ../wolfi-packages \
          --package-repo-url "https://packages.wolfi.dev/os"
