name: Validate

on:
  pull_request:
    branches: ['main']
  push:
    branches:
      - gh-readonly-queue/main/**

jobs:
  lint:
    name: Validate
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v3

    - name: Validate advisory data
      id: validate
      uses: docker://ghcr.io/wolfi-dev/sdk:latest@sha256:bb5769922852c5a389e7ef2dfaab1d07312dd2cbad66552df77dfefe4c1d022d
      with:
        entrypoint: wolfictl
        args: advisory validate --no-distro-detection --advisories-repo-dir .
