name: Validate

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - gh-readonly-queue/main/**

jobs:
  lint:
    name: Validate
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        path: './wolfi-advisories'

    - name: 'Clone Wolfi packages repository'
      uses: actions/checkout@v4
      with:
        repository: 'wolfi-dev/os'
        fetch-depth: 0
        path: './wolfi-packages'
        ref: 'main'

    - name: get fork point
      id: fork-point
      working-directory: ./wolfi-advisories
      run: |
        fork_point=$(git merge-base --fork-point refs/remotes/origin/${{ github.base_ref }} HEAD || git rev-parse HEAD)
        echo "fork point will be $fork_point"
        echo "fork_point=$fork_point" >> $GITHUB_OUTPUT

    - uses: wolfi-dev/actions/advisories-validate@main
      with:
        fork_point: ${{ steps.fork-point.outputs.fork_point }}
        advisories-directory: './wolfi-advisories'
        packages-directory: './wolfi-packages'
        repository: ${{ github.repository }}
        package-repo-url: 'https://packages.wolfi.dev/os'
        token: ${{ secrets.GITHUB_TOKEN }}
