name: Validate

on:
  pull_request:
    branches: ['main']
  push:
    branches:
      - gh-readonly-queue/main/**

jobs:
  lint:
    name: Validate
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v3

    - name: Validate advisory data
      id: validate
      uses: docker://ghcr.io/wolfi-dev/sdk:latest@sha256:34d80ae999164342404b149b6d24044d488b8aa3d6bd772726b66f43804116ab
      with:
        entrypoint: wolfictl
        args: advisory validate --no-distro-detection --advisories-repo-dir .
