name: Validate

on:
  pull_request:
    branches: ['main']
  push:
    branches:
      - gh-readonly-queue/main/**

jobs:
  lint:
    name: Validate
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v3

    - name: Validate advisory data
      id: validate
      uses: docker://ghcr.io/wolfi-dev/sdk:latest@sha256:738c4b4c1ed8aa5c0510d9fe6eece1e98a40cec0a8f4c39e44c96b97af204b20
      with:
        entrypoint: wolfictl
        args: advisory validate --no-distro-detection --advisories-repo-dir .
